server:
  host: "localhost"
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "pass123test"
  name: "service_monitor"
  ssl_mode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

twilio:
  account_sid: ""
  auth_token: ""
  from_number: ""

jwt:
  secret_key: "your-secret-key"
  duration: 24 # hours 