database:
  host: localhost
  port: 5432
  user: postgres
  password: pass123test
  dbName: service_monitor
  sslMode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

twilio:
  accountSID: "your_account_sid"
  authToken: "your_auth_token"
  fromPhone: "+1234567890"

server:
  host: 0.0.0.0
  port: 8080 